version: '3'

services:
  planner:
    build: ./planner
    ports:
      - "8080:8080"
    depends_on:
      - worker
      - worker2
      - worker3
      - worker4
    env_file:
      - .env

  worker:
    build: ./worker
    environment: 
      - PORT=3000
    # - ADD=true
    ports:
      - "3000:3000"
    env_file:
      - .env
    extra_hosts:
      - host.docker.internal:host-gateway

  worker2 : 
    environment: 
      - PORT=3001
  #   - MULT=true
    build : ./worker
    image : worker2
    ports: 
      - "3001:3001"
    container_name: worker2
    extra_hosts:
      - host.docker.internal:host-gateway
    
  worker3 : 
    environment: 
        - PORT=3003
    build : ./worker
    image : worker3
    ports: 
        - "3003:3003"
    container_name: worker3
    extra_hosts:
        - host.docker.internal:host-gateway

  worker4 : 
    environment: 
        - PORT=3004
    build : ./worker
    image : worker4
    ports: 
        - "3004:3004"
    container_name: worker4
    extra_hosts:
        - host.docker.internal:host-gateway