version: '3'

services:
  planner:
    build: ./planner
    ports:
      - "3000:3000"
    env_file:
      - .env

  worker:
    build: ./worker
    ports:
      - "8081:3000"
    env_file:
      - .env
